spring:
  application:
    name: inventory-failover
  zipkin:
    baseUrl: http://localhost:9411/
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://netflix:eureka@localhost:8761/eureka